name: voice_message_recorder
description: "best way to record voice like whatsapp"
version: 0.0.1
homepage: https://github.com/Moeed366/

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.1.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  cupertino_icons: ^1.0.8
  # uuid: ^3.0.7
  permission_handler: ^11.3.1
  animated_text_kit: ^4.2.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  record: ^5.2.0
  audioplayers: ^6.1.0
  emoji_picker_flutter: ^3.1.0
  camera: ^0.11.0+2
  video_player: ^2.9.2
  file_picker: ^8.1.3
  flutter_native_contact_picker: ^0.0.9
  json_annotation: ^4.9.0
  flutter_multi_formatter: ^2.13.0
  country_flags: ^3.0.0
  flutter_cache_manager: ^3.4.1
  just_audio: ^0.9.42
  syncfusion_flutter_sliders: ^27.1.58



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.voice_message_recorder
        pluginClass: VoiceMessageRecorderPlugin
      ios:
        pluginClass: VoiceMessageRecorderPlugin
      linux:
        pluginClass: VoiceMessageRecorderPlugin
      macos:
        pluginClass: VoiceMessageRecorderPlugin
      windows:
        pluginClass: VoiceMessageRecorderPluginCApi
      web:
        pluginClass: VoiceMessageRecorderWeb
        fileName: voice_message_recorder_web.dart

  assets:
    - assets/
    - assets/sounds/delete.mp3
    - assets/sounds/record.mp3

